@startuml

interface "LoggerInterface" {
  createLogger(level, path, consoleLogEnabled)
  setLogLevel(level)
  setLogFilePath(path)
  enableConsoleLog()
  disableConsoleLog()
  writeLogMessage(level, string)
}

@enduml
