@startuml

package "logger" {
  !include "../external_view/interfaces/logger.puml"

  enum "LogLevels" {
    DEBUG
    INFO
    WARNING
    ERROR
    CRITICAL
  }

  class "Logger" {
    - bool isConsoleLoggingEnabled
    - file logFile
    - thread loggerThread
    - queue loggerQueue
    - map levelMapping

    + createLogger(LogLevels level, String path, Bool consoleLogEnabled)
    + setLogLevel(LogLevels level)
    + setLogFilePath(path)
    + enableConsoleLog()
    + disableConsoleLog()
    + writeLogMessage(LogLevels level, arguments)
  }
}

"Logger" --|> "LoggerInterface"
"Logger" -- "LogLevels"

@enduml
